/**
 * Type definitions for flexible form submissions with Gemini AI normalization
 */

/**
 * Standardized schema that all form submissions are normalized to
 */
export interface NormalizedFormData {
  // Customer information
  first_name?: string;
  last_name?: string;
  email?: string;
  phone_number?: string;

  // Address information
  street_address?: string;
  city?: string;
  state?: string;
  zip?: string;

  // Service request details
  pest_issue?: string;
  own_or_rent?: 'own' | 'rent' | 'unknown';
  additional_comments?: string;
}

/**
 * Ticket metadata generated by Gemini from form content
 */
export interface TicketMetadata {
  description: string; // Generated ticket description
  priority?: 'low' | 'medium' | 'high' | 'urgent';
  service_type?: 'Support' | 'Sales'; // Department routing
  pest_type?: string; // e.g., "Rodent Control", "Mosquito Control", "Bed Bug Control"
}

/**
 * Result from Gemini AI parsing
 */
export interface GeminiParseResult {
  normalized: NormalizedFormData;
  ticket: TicketMetadata;
  confidence: number; // 0.0 - 1.0
  success: boolean;
  error?: string;
}

/**
 * Database record for form_submissions table
 */
export interface FormSubmission {
  id: string;
  company_id: string | null;
  ticket_id: string | null;
  customer_id: string | null;

  source_url: string | null;
  source_domain: string | null;

  raw_payload: Record<string, any>;
  normalized_data: NormalizedFormData | null;
  content_type: string | null;

  gemini_confidence: number | null;
  processing_status: 'pending' | 'processed' | 'failed';
  processing_error: string | null;

  ip_address: string | null;
  user_agent: string | null;

  processed_at: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * API response for form submission webhook
 */
export interface FormSubmissionResponse {
  success: boolean;
  submissionId?: string;
  ticketId?: string;
  customerId?: string;
  error?: string;
}
