ALTER TABLE company_pricing_settings
ADD COLUMN IF NOT EXISTS base_yard_sq_ft INTEGER NOT NULL DEFAULT 5000,
ADD COLUMN IF NOT EXISTS yard_sq_ft_interval INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN IF NOT EXISTS max_yard_sq_ft INTEGER NOT NULL DEFAULT 20000;
